apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  profile: demo
  components:
    base:
      enabled: true
    pilot:
      enabled: true
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          service:
            type: LoadBalancer
            ports:
              - port: 30080
                targetPort: 8080
                name: http2
              - port: 30443
                targetPort: 8443
                name: https
    egressGateways:
      - name: istio-egressgateway
        enabled: true
        k8s:
          service:
            type: ClusterIP
            ports:
              - port: 30080
                targetPort: 8080
                name: http2
              - port: 30443
                targetPort: 8443
                name: https
