apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  namespace: istio-system
  name: kiali
spec:
  auth:
    strategy: anonymous
  deployment:
    service_type: "NodePort"
  external_services:
    tracing:
      enabled: true
      in_cluster_url: "http://jaeger-query.istio-system.svc.cluster.local:16685/jaeger"
      use_grpc: true
      whitelist_istio_system: ["jaeger-query", "istio-ingressgateway"]
